services:
  mongo:
    image: mongo:7
    container_name: cron_queue_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  # backend:
  #   build: ./backend
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/cron_queue_monitor
  #   depends_on:
  #     - mongo

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:4000
  #   depends_on:
  #     - backend

volumes:
  mongo_data:
